baseURL = "https://khaiverse.github.io/khaiweb/"
languageCode = "en-us"
title = "Khaiverse"
contentDir = "content"
paginate = 5

[taxonomies]
  label = "labels"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
