baseURL = "https://khaiverse.github.io/khaiverse-web/"
languageCode = "en-us"
title = "Khaiverse"
theme = ""
contentDir = "content"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
